### ISSUE TITLE
Error while obtaining my external IP address

### ISSUE THREAD

**Issue by MrPointer** [lontivero/Open.NAT#26]
A week ago I tried the library for the 1st time, so to see if it works OK I ran the official test that @lontivero  has specified, but it failed almost right away.
The problem occurs to be a bad Http request, in the method GetExternalIPAddressResponse.
Here's a log file I've added to show the exception being thrown along with the built-in tracing:
```
23 Apr 2015 15:02:36
Type: System.InvalidOperationException
Abbreviated Message: The response is invalid: GetExternalIPAddressResponse

Full message: System.InvalidOperationException: The response is invalid: GetExternalIPAddressResponse
   at Open.Nat.ResponseMessageBase.GetNode() in ****\Open.NAT-master\Open.NAT-master\Open.Nat\Upnp\ResponseMessageBase.cs:line 55
   at Open.Nat.GetExternalIPAddressResponseMessage..ctor(XmlDocument response, String serviceType) in ****\Open.NAT-master\Open.NAT-master\Open.Nat\Upnp\Messages\Responses\GetExternalIPAddressResponseMessage.cs:line 39
   at Open.Nat.UpnpNatDevice.<GetExternalIPAsync>d__0.MoveNext() in ****\Open.NAT-master\Open.NAT-master\Open.Nat\Upnp\UpnpNatDevice.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Open.Nat.ConsoleTest.NatTest.<Test>d__0.MoveNext() in ****\Open.NAT-master\Open.NAT-master\Open.Nat.ConsoleTest\Main.cs:line 69

In: ****\Open.NAT-master\Open.NAT-master\Open.Nat.ConsoleTest\Main.cs; at: MoveNext; line: 69; column: 17
***************************

Console output:

Open.NAT - Information > Start Discovery
Open.NAT - Information > Searching for: UpnpSearcher
Open.NAT - Verbose > UPnP Response: HTTP/1.1 200 OK
ST: urn:schemas-upnp-org:service:WANIPConnection:1
LOCATION: http://10.0.0.138:5000/Public_UPNP_gatedesc.xml
SERVER: Linux/2.6.12, UPnP/1.0, NETGEAR-UPNP/1.0
EXT:
CACHE-CONTROL: max-age=3600
USN: uuid:8aa1037d-ff05-ae35-3258-ecc39d365000::urn:schemas-upnp-org:service:WAN
IPConnection:1


Open.NAT - Information > UPnP Response: Router advertised a 'urn:schemas-upnp-or
g:service:WANIPConnection:1' service!!!
Open.NAT - Information > Found device at: http://10.0.0.138:5000/Public_UPNP_gat
edesc.xml
Open.NAT - Information > 10.0.0.138:5000: Fetching service list
Open.NAT - Information > Found device at: http://10.0.0.138:5000/Public_UPNP_gat
edesc.xml
Open.NAT - Information > 10.0.0.138:5000: Parsed services list
Open.NAT - Information > 10.0.0.138:5000: Found service: urn:schemas-upnp-org:se
rvice:WANIPConnection:1
Open.NAT - Information > 10.0.0.138:5000: Found upnp service at: /Public_UPNP_C3

Open.NAT - Information > 10.0.0.138:5000: Handshake Complete
Open.NAT - Information > Stop Discovery
Open.NAT - Verbose > SOAPACTION: **GetExternalIPAddress** url:http://10.0.0.138:
5000/Public_UPNP_C3
Open.NAT - Verbose > <s:Envelope
   xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"
   s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
   <s:Body>
      <u:GetExternalIPAddress xmlns:u="urn:schemas-upnp-org:service:WANIPConnect
ion:1">
      </u:GetExternalIPAddress>
   </s:Body>
</s:Envelope>


Open.NAT - Verbose > WebException status: ProtocolError
Open.NAT - Verbose > Response:
<html>
  <head>
    <title>400 Bad Request</title>
  </head>
  <body>
    <h1>400 Bad Request</h1>
    <p>This server does not support the operation requested by your client.</p>
  </body>
</html>

Socket listening on port 1602. Remember, it is mapped to external port 1702!!!
Test it with http://www.canyouseeme.org/ online tool
```

I've also tried restarting my router, assigning a static IP address, and using the NATUPnP 1.0 type library, which actually works just fine.

**Comment by lontivero** [comment]
@MrPointer there is a new version with better tracing capabilities that can help us to understand this issue. After running the ConsoleTest program, you will find a new "network.log" file in the bin\Debug folder. Could you share it with me? Thx.

**Comment by MrPointer** [comment]
Here's the output of the new log file:
```
Open.NAT Information: 0 : Start Discovery
Open.NAT Information: 0 : Searching for: UpnpSearcher
Open.NAT Information: 0 : UPnP Response: Router advertised a 'urn:schemas-upnp-org:service:WANIPConnection:1' service!!!
Open.NAT Information: 0 : Found device at: http://10.0.0.138:5000/Public_UPNP_gatedesc.xml
Open.NAT Information: 0 : 10.0.0.138:5000: Fetching service list
Open.NAT Information: 0 : Found device at: http://10.0.0.138:5000/Public_UPNP_gatedesc.xml
System.Net Verbose: 0 : [6948] WebRequest::Create(http://10.0.0.138:5000/Public_UPNP_gatedesc.xml)
System.Net Verbose: 0 : [6948] HttpWebRequest#14854669::HttpWebRequest(http://10.0.0.138:5000/Public_UPNP_gatedesc.xml#1714163072)
System.Net Error: 0 : [6948] Can't retrieve proxy settings for Uri 'http://10.0.0.138:5000/Public_UPNP_gatedesc.xml'. Error code: 12180.
System.Net Information: 0 : [6948] HttpWebRequest#14854669 - Request: GET /Public_UPNP_gatedesc.xml HTTP/1.1

System.Net Information: 0 : [6948] ConnectStream#14701735 - Sending headers
{
ACCEPT-LANGUAGE: en
Host: 10.0.0.138:5000
Connection: Keep-Alive
}.
System.Net Information: 0 : [6948] Connection#55082781 - Received status line: Version=1.1, StatusCode=200, StatusDescription=OK.
System.Net Information: 0 : [6948] Connection#55082781 - Received headers
{
Connect: close
Pragma: no-cache
Content-Length: 4138
Cache-Control: no-cache
Content-Type: text/xml
Server: Linux/2.6.12 UPnP/1.0 NETGEAR-UPNP/1.0
}.
System.Net Verbose: 0 : [6948] <<<?xml version="1.0"?>
<root xmlns="urn:schemas-upnp-org:device-1-0">
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<URLBase>http://10.0.0.138:5000/</URLBase>
<device>
<deviceType>urn:schemas-upnp-org:device:InternetGatewayDevice:1</deviceType>
<friendlyName>VEGN2610 (Gateway)</friendlyName>
<manufacturer>NETGEAR, Inc.</manufacturer>
<manufacturerURL>http://www.NETGEAR.com</manufacturerURL>
<modelDescription>NETGEAR VEGN2610 N300 Wireless Router</modelDescription>
<modelNumber>VEGN2610</modelNumber>
<modelName>VEGN2610</modelName>
<modelURL>http://www.netgear.com/Products/RoutersandGateways/RangeMaxNEXTWirelessRoutersandGateways/VEGN2610.aspx</modelURL>
<UDN>uuid:d95d9fe3-b6bc-8518-3996-67b0dd3687fd</UDN>
<iconList>
<icon>
<mimetype>image/x-icon</mimetype>
<width>64</width>
<height>64</height>
<depth>32</depth>
<url>http://10.0.0.138/upnp.ico</url>
</icon>
</iconList>
<serviceList>
<service>
<serviceType>urn:schemas-upnp-org:service:Layer3Forwarding:1</serviceType>
>>
System.Net Verbose: 0 : [6948] <<
<serviceId>urn:upnp-org:serviceId:L3Forwarding1</serviceId>
<SCPDURL>/Public_UPNP_Layer3F.xml</SCPDURL>
<controlURL>/Public_UPNP_C1</controlURL>
<eventSubURL>/Public_UPNP_Event_1</eventSubURL>
</service>
</serviceList>
<deviceList>
<device>
<deviceType>urn:schemas-upnp-org:device:WANDevice:1</deviceType>
<friendlyName>WAN Device</friendlyName>
<manufacturer>NETGEAR, Inc.</manufacturer>
<manufacturerURL>http://www.NETGEAR.com</manufacturerURL>
<modelDescription>NETGEAR VEGN2610 N300 Wireless Router</modelDescription>
<modelNumber>VEGN2610</modelNumber>
<modelName>VEGN2610</modelName>
<modelURL>http://www.netgear.com/Products/RoutersandGateways/RangeMaxNEXTWirelessRoutersandGateways/VEGN2610.aspx</modelURL>
<UDN>uuid:ec97effb-bbb9-ae6a-30a3-33a1e761b436</UDN>
<iconList>
<icon>
<mimetype>image/x-icon</mimetype>
<width>64</width>
<height>64</height>
<depth>32</depth>
<url>http://10.0.0.138/upnp.ico</url>
</icon>
</iconList>
<serviceList>
<service>
<serviceType>urn:schemas-upnp-org:ser>>
System.Net Verbose: 0 : [6948] <<vice:WANCommonInterfaceConfig:1</serviceType>
<serviceId>urn:upnp-org:serviceId:WANCommonIFC1</serviceId>
<SCPDURL>/Public_UPNP_WAND.xml</SCPDURL>
<controlURL>/Public_UPNP_C2</controlURL>
<eventSubURL>/Public_UPNP_Event_2</eventSubURL>
</service>
</serviceList>
<deviceList>
<device>
<deviceType>urn:schemas-upnp-org:device:WANConnectionDevice:1</deviceType>
<friendlyName>WAN Connection Device</friendlyName>
<manufacturer>NETGEAR, Inc.</manufacturer>
<manufacturerURL>http://www.NETGEAR.com</manufacturerURL>
<modelDescription>NETGEAR VEGN2610 N300 Wireless Router</modelDescription>
<modelNumber>VEGN2610</modelNumber>
<modelName>VEGN2610</modelName>
<modelURL>http://www.netgear.com/Products/RoutersandGateways/RangeMaxNEXTWirelessRoutersandGateways/VEGN2610.aspx</modelURL>
<UDN>uuid:8aa1037d-ff05-ae35-3258-ecc39d365000</UDN>
<iconList>
<icon>
<mimetype>image/x-icon</mimetype>
<width>64</width>
<height>64</height>
<depth>32</depth>
<url>http://10.0.0.138/upnp.ico</url>
</icon>
</iconList>
>>
System.Net Verbose: 0 : [6948] <<
<serviceList>
<service>
<serviceType>urn:schemas-upnp-org:service:WANEthernetLinkConfig:1</serviceType>
<serviceId>urn:upnp-org:serviceId:WANEthLinkC1</serviceId>
<SCPDURL>/Public_UPNP_WANEtherLinkCfg.xml</SCPDURL>
<controlURL>/Public_UPNP_C4</controlURL>
<eventSubURL>/Public_UPNP_Event_4</eventSubURL>
</service>
<service>
<serviceType>urn:schemas-upnp-org:service:WANIPConnection:1</serviceType>
<serviceId>urn:upnp-org:serviceId:WANIPConn1</serviceId>
<SCPDURL>/Public_UPNP_WANIPConn.xml</SCPDURL>
<controlURL>/Public_UPNP_C3</controlURL>
<eventSubURL>/Public_UPNP_Event_3</eventSubURL>
</service>
<service>
<serviceType>urn:schemas-upnp-org:service:WANPPPConnection:1</serviceType>
<serviceId>urn:upnp-org:serviceId:WANPPPConn1</serviceId>
<SCPDURL>/Public_UPNP_WANPPPConn.xml</SCPDURL>
<controlURL>/Public_UPNP_C5</controlURL>
<eventSubURL>/Public_UPNP_Event_5</eventSubURL>
</service>
</serviceList>
</device>
</deviceList>
</device>
</deviceList>
<presentationURL>http://www.routerlogin.n>>
System.Net Verbose: 0 : [6948] <<et</presentationURL>
</device>
</root>
>>
Open.NAT Information: 0 : 10.0.0.138:5000: Parsed services list
Open.NAT Information: 0 : 10.0.0.138:5000: Found service: urn:schemas-upnp-org:service:WANIPConnection:1
Open.NAT Information: 0 : 10.0.0.138:5000: Found upnp service at: /Public_UPNP_C3
Open.NAT Information: 0 : 10.0.0.138:5000: Handshake Complete
Open.NAT Information: 0 : Stop Discovery
Open.NAT Information: 0 : GetExternalIPAsync - Getting external IP address
System.Net Verbose: 0 : [6948] WebRequest::Create(http://10.0.0.138:5000/Public_UPNP_C3)
System.Net Verbose: 0 : [6948] HttpWebRequest#47674696::HttpWebRequest(http://10.0.0.138:5000/Public_UPNP_C3#-240489888)
System.Net Information: 0 : [3640] HttpWebRequest#47674696 - Request: POST /Public_UPNP_C3 HTTP/1.1

System.Net Information: 0 : [3640] ConnectStream#43257534 - Sending headers
{
Content-Type: text/xml; charset="utf-8"
SOAPACTION: "urn:schemas-upnp-org:service:WANIPConnection:1#GetExternalIPAddress"
Host: 10.0.0.138:5000
Content-Length: 302
Expect: 100-continue
Connection: Close
}.
System.Net Verbose: 0 : [6004] <<<s:Envelope 
   xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" 
   s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
   <s:Body>
      <u:GetExternalIPAddress xmlns:u="urn:schemas-upnp-org:service:WANIPConnection:1">
      </u:GetExternalIPAddress>
   </s:Body>
</s:Envelope>

>>
System.Net Information: 0 : [3724] Connection#46853828 - Received status line: Version=1.0, StatusCode=400, StatusDescription=Bad Request.
System.Net Information: 0 : [3724] Connection#46853828 - Received headers
{
Content-Type: text/html
}.
System.Net Verbose: 0 : [3724] <<<html>
<head><title>400 Bad Request</title></head>
<body><h1>400 Bad Request</h1>
<p>This server does not support the operation requested by your client.</p></body>
</html>
>>
System.Net Error: 0 : [3724] Exception in HttpWebRequest#47674696::EndGetResponse - The remote server returned an error: (400) Bad Request..
System.Net Error: 0 : [0840] Exception in AppDomain#48649253::UnhandledExceptionHandler - One or more errors occurred..
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Open.Nat.ConsoleTest.NatTest.Main(String[] args) in d:\Timor - Programs\Open.NAT-master\Open.Nat.ConsoleTest\Main.cs:line 42
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

**Comment by lontivero** [comment]
Thank you very much. I can see the router provides two service interfaces:

    <serviceType>urn:schemas-upnp-org:service:WANIPConnection:1</serviceType>
    <controlURL>/Public_UPNP_C3</controlURL>

and

    <serviceType>urn:schemas-upnp-org:service:WANPPPConnection:1</serviceType>
    <controlURL>/Public_UPNP_C5</controlURL>

Open.NAT uses the first one and maybe it should try with both. I have to see what the UPnP specs says about this situation.

**Comment by lontivero** [comment]
@MrPointer could you share with me these two xml files?

* http://10.0.0.138:5000/Public_UPNP_WANIPConn.xml
* http://10.0.0.138:5000/Public_UPNP_WANPPPConn.xml

They have the services description for the two services available in your router. This is, the list of supported operations.

**Comment by MrPointer** [comment]
@lontivero Do you mean simply to open them in my PC and publish the results here?

**Comment by lontivero** [comment]
Yes, 10.0.0.138 is your router IP. 5000 is the port number where the services are listening and those xml files are the service descriptions. You should open them in your PC and publish them here or in pastebin (pastebin is problably the best place). With those files I will be able to see what kind of operations those services allow.

**Comment by MrPointer** [comment]
@lontivero OK got it, just wanted to be sure!
Here's the link to the 1st one: [UPnP WANIPConn](http://pastebin.com/L5wP6hky)
Here's the link to the 2nd one: [UPnP WANPPPConn](http://pastebin.com/NZ7hmPVR)

**Comment by lontivero** [comment]
I am sure the problem is Open.NAT is sending the request to the wrong service. You can verify this simply removing all the allowed serviceTypes in UpnpSearcher class by **WANPPPConnection:1**:

    internal class UpnpSearcher : Searcher
    {
        //.........
        private static readonly string[] ServiceTypes = new[]{
            "WANIPConnection:2", 
            "WANPPPConnection:2",
            "WANIPConnection:1", 
            "WANPPPConnection:1" 
        };

It should be:

    internal class UpnpSearcher : Searcher
    {
        //.........
        private static readonly string[] ServiceTypes = new[]{
            "WANPPPConnection:1" 
        };

If with this Open.NAT works, it means that I will need to implement a mechanism that let Open.NAT knows what service it has to use.

**Comment by MrPointer** [comment]
@lontivero Apparently it didn't solve the whole thing but I do get a different error now.
Here's the "Network.log" file's output: [Network.log](http://pastebin.com/N0zdPzj6)

**Comment by lontivero** [comment]
@MrPointer it is the same error: 400 Bad request. We tried w/ WANIPConnection and WANPPPConnection and both failed in the same way. The log file wasn't usefull, sadly. 

I didn't want to get to this point but, the only way to catch this defect will be running wireshark (or other TCP sniffer) and record the traffic between your program using NATUPnP 1.0 type library. It is impossible for me to know what is going on so, I will need to see how NATUPnP 1.0 is doing it.

**Comment by MrPointer** [comment]
@lontivero I got a different exception this time so I thought it's a different error, my bad.
I think that I also should point out that using NATUPnP I didn't query my external IP like I told you already, I did it using a web page through a web request, maybe it'll help.
Now about Wireshark, I'm familiar with the program but never really understood what to do with and how it works, and unfortunately I don't have the required time now to explore it. If you'd guide me with a step-by-step tutorial in order to help you, I gladly will :)

**Comment by lontivero** [comment]
@MrPointer that's not what I see. I see the same error code and description (400 Bad Request). 

You always can know you external ip address using a web site tool on internet and that's okey, We don't need Open.NAT if that's the only thing we want to know. 

The problem now is that we don't know if other tools or libraries can communitace, using Upnp, with your router or not.  We tried with the two published services without luck even when the messages were well formed.

**Next steps**:
* Check Upnp is enabled in your router. It seems to be but anyway, this is the first thing to do.
* Find an application that perform portforwarding using Upnp (skype, torrent clients, etc) and record the TCP traffic.

**Comment by MrPointer** [comment]
@lontivero Yes, UPnP **is** enabled on my router hence I could use the NATUPnP 1.0 type library.
Moreover, send and receive communications work just fine, as the ports are forwarded properly.

I think you misunderstood me when I asked a step-by-step guidance. I'm not familiar at all with Wireshark's interface, meaning I'm completely lost when I open the program. I need some guidance from you on what exactly to do in it to record the TCP traffic and send it over to you.
Again, I'm very sorry if it burdens you I just don't have the required time right now to learn it all by myself.

**Comment by Mailaender** [comment]
We may have stumbled upon the same issue: https://github.com/OpenRA/OpenRA/pull/10281#issuecomment-167225923
