### ISSUE TITLE
Cannot find router when the router is not hosted at 192.168.0.1

### ISSUE THREAD

**Issue by adotout** [lontivero/Open.NAT#36]
My router defaulted to 192.168.1.1 and was not discoverable. I changed the ip to 192.168.0.1 and it started working.

**Comment by lontivero** [comment]
@adotout my router is not at 192.168.0.1 and Open.NAT can discover it well. Also, I have UPnp test services hosted at 127.0.0.1 and 10.0.0.2 and they are discovered with no problem. I think it has to be something dífferent and no related to ip address. Could you please share the network log here?

**Comment by adotout** [comment]
It looks like the network log at the time it wasn't working is fairly empty. I'm no longer able to reproduce the issue regardless of the port the router is on. It seems like my router must have been having an issue that was resolved by the reboot required to change the port from 192.168.0.1 -> 192.168.1.1. 

Thanks for taking a look, closing because I can no longer reproduce.

The network log, for the record:

Open.NAT Information: 0 : Start Discovery
Open.NAT Information: 0 : Searching for: UpnpSearcher
Open.NAT Information: 0 : Stop Discovery
Open.NAT Information: 0 : Device not found. Common reasons:
Open.NAT Information: 0 : 	* No device is present or,
Open.NAT Information: 0 : 	* Upnp is disabled in the router or
Open.NAT Information: 0 : 	* Antivirus software is filtering SSDP (discovery protocol).
System.Net Error: 0 : [12372] Exception in AppDomain#12547953::UnhandledExceptionHandler - One or more errors occurred..
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Open.Nat.ConsoleTest.NatTest.Main(String[] args) in C:\Users\behrlich\Desktop\Open.NAT\Open.Nat.ConsoleTest\Main.cs:line 42
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
