### ISSUE TITLE
ConflictInMappingEntry giant exception

### ISSUE THREAD

**Issue by mcmonkey4eva** [lontivero/Open.NAT#42]
What does this exception mean:
```
2016/07/20 01:01:46 UTC-07:00 [ERROR] Trying to open port 28010: System.AggregateException: One or more errors occurred. ---> Open.Nat.MappingException: Error 718: ConflictInMappingEntry
   at Open.Nat.SoapClient.GetXmlDocument(String response) in C:\Github\Open.NAT\Open.Nat\Upnp\SoapClient.cs:line 247
   at Open.Nat.SoapClient.<InvokeAsync>d__3.MoveNext() in C:\Github\Open.NAT\Open.Nat\Upnp\SoapClient.cs:line 129
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Open.Nat.StreamExtensions.<TimeoutAfter>d__7`1.MoveNext() in C:\Github\Open.NAT\Open.Nat\Utils\Extensions.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Open.Nat.UpnpNatDevice.<CreatePortMapAsync>d__4.MoveNext() in C:\Github\Open.NAT\Open.Nat\Upnp\UpnpNatDevice.cs:line 185
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
```
?

**Comment by lontivero** [comment]
It means the specified external port is already assigned to another client. For more info please take a look at the [WANIPConnection:1 Service Template Version 1.01](http://www.upnp.org/specs/gw/UPnP-gw-WANIPConnection-v1-Service.pdf) -page 26-Errors section

**Comment by mcmonkey4eva** [comment]
Ah, thanks.

Any chance we could get the common/expected exception messages replaced with clearer information?

IE something like "`Open.Nat.MappingException: Error 718: ConflictInMappingEntry - External port is already assigned to another client`"
and additionally, thrown at the correct level rather than 5 layers deep into in the innermost code.
So the stacktrace would be like
```
at Open.Nat.Whatever.ApplyTheThing() in Open.NAT
at YourCode.OpenSomePorts() in YourProject
```

**Comment by lontivero** [comment]
Sure, feel free to send a PR and I will merge it.
