### ISSUE TITLE
Error 402: invalid args

### ISSUE THREAD

**Issue by mcmonkey4eva** [lontivero/Open.NAT#61]
Here's an interesting error a user got during routine use of my program (Which opens a port publicly as a default action, regardless of whether that port is immediately used)
```
Trying to open port 28010: System.AggregateException: One or more errors occurred. ---> Open.Nat.MappingException: Error 402: Invalid Args
   at Open.Nat.SoapClient.GetXmlDocument(String response) in C:\Github\Open.NAT\Open.Nat\Upnp\SoapClient.cs:line 247
   at Open.Nat.SoapClient.<InvokeAsync>d__3.MoveNext() in C:\Github\Open.NAT\Open.Nat\Upnp\SoapClient.cs:line 129
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Open.Nat.StreamExtensions.<TimeoutAfter>d__7`1.MoveNext() in C:\Github\Open.NAT\Open.Nat\Utils\Extensions.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Open.Nat.UpnpNatDevice.<DeletePortMapAsync>d__5.MoveNext() in C:\Github\Open.NAT\Open.Nat\Upnp\UpnpNatDevice.cs:line 236
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Voxalia.ServerGame.NetworkSystem.NetworkBase.Init()
---> (Inner Exception #0) Open.Nat.MappingException: Error 402: Invalid Args
   at Open.Nat.SoapClient.GetXmlDocument(String response) in C:\Github\Open.NAT\Open.Nat\Upnp\SoapClient.cs:line 247
   at Open.Nat.SoapClient.<InvokeAsync>d__3.MoveNext() in C:\Github\Open.NAT\Open.Nat\Upnp\SoapClient.cs:line 129
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Open.Nat.StreamExtensions.<TimeoutAfter>d__7`1.MoveNext() in C:\Github\Open.NAT\Open.Nat\Utils\Extensions.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Open.Nat.UpnpNatDevice.<DeletePortMapAsync>d__5.MoveNext() in C:\Github\Open.NAT\Open.Nat\Upnp\UpnpNatDevice.cs:line 236<---
 
```

**Comment by lontivero** [comment]
The router doesn't accept the request because it is not valid. It can be because the port is already opened, because the specified host is wrong or not allowed, etc.
