### ISSUE TITLE
SocketException running console test

### ISSUE THREAD

**Issue by robochase6000** [lontivero/Open.NAT#63]
seeing this error spam ~6 times or so when i try running the open.nat console test  - disregard the exact line numbers because i have some other logs in there currently, but this is the line it's failing on in PmpSearcher -

`client.Send(buffer, buffer.Length, gatewayEndpoint);`

`
Open.NAT - Error > System.Net.Sockets.SocketException (0x80004005): The system detected an invalid pointer address in attempting to use a pointer argument in a call
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
   at System.Net.Sockets.UdpClient.Send(Byte[] dgram, Int32 bytes, IPEndPoint endPoint)
   at Open.Nat.PmpSearcher.Discover(UdpClient client, CancellationToken cancelationToken) in C:\Users\chase\Downloads\Open.NAT-master\Open.NAT-master\Open.Nat\Pmp\PmpSearcher.cs:line 121
   at Open.Nat.Searcher.Discover(CancellationToken cancelationToken) in C:\Users\chase\Downloads\Open.NAT-master\Open.NAT-master\Open.Nat\Discovery\Searcher.cs:line 86
`

at the end of the log, i get this message that it can't find a device.  just wondering if the above error is interfering with the test, or if that is indeed supposed to happen.

> Open.NAT - Information > Device not found. Common reasons:
> Open.NAT - Information >        * No device is present or,
> Open.NAT - Information >        * Upnp is disabled in the router or
>  Open.NAT - Information >        * Antivirus software is filtering SSDP (discovery protocol).

**Comment by lontivero** [comment]
Open.NAT tries to send SSDP messages to all the existing interfaces, many of those could fail with that error. However, it should find your device anyway. Please, send me the network.log file to review what the problem can be.
